<a href="https://colab.research.google.com/github/piyush9835/college-ml/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy


In [ ]:
arr = np.arange(0, 10, 2)
print(arr)


[0 2 4 6 8]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)


[1 2 3]


In [ ]:
arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.zeros((2, 3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.ones((3, 2))
print(arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.full((2, 2), 7)
print(arr)


[[7 7]
 [7 7]]


In [ ]:
arr = np.random.rand(2, 3)
print(arr)


[[0.22669731 0.11333484 0.06722348]
 [0.20432844 0.73413322 0.37603595]]


In [ ]:
arr = np.random.randn(2, 3)
print(arr)


[[ 1.71293789 -0.19191938 -0.5254704 ]
 [-2.34189984  1.52255823  0.647459  ]]


In [ ]:
arr = np.random.randint(0, 10, size=(2, 3))
print(arr)



[[0 2 4]
 [3 6 4]]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr.shape)


(2, 2)


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.size)


4


In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)



2


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)



[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
transposed = np.transpose(arr)
print(transposed)


[[1 3]
 [2 4]]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
flattened = arr.flatten()
print(flattened)


[1 2 3 4]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate((arr1, arr2))
print(concatenated)


[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
split = np.split(arr, 3)
print(split)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = np.vstack((arr1, arr2))
print(stacked)


[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = np.hstack((arr1, arr2))
print(stacked)


[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4])
total = np.sum(arr)
print(total)



10


In [ ]:
arr = np.array([1, 2, 3, 4])
mean_value = np.mean(arr)
print(mean_value)


2.5


In [ ]:
arr = np.array([1, 2, 3, 4])
median_value = np.median(arr)
print(median_value)


2.5


In [ ]:
arr = np.array([1, 2, 3, 4])
median_value = np.median(arr)
print(median_value)



2.5


In [ ]:
arr = np.array([1, 2, 3, 4])
std_dev = np.std(arr)
print(std_dev)


1.118033988749895


In [ ]:
arr = np.array([1, 2, 3, 4])
min_value = np.min(arr)
print(min_value)


1


In [ ]:
arr = np.array([1, 2, 3, 4])
max_value = np.max(arr)
print(max_value)


4


In [ ]:
arr = np.array([1, 2, 3, 4])
min_index = np.argmin(arr)
print(min_index)


0


In [ ]:
arr = np.array([1, 2, 3, 4])
max_index = np.argmax(arr)
print(max_index)


3


In [ ]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
dot_product = np.dot(arr1, arr2)
print(dot_product)


11


In [ ]:
arr = np.array([[1, 2], [3, 4]])
inv_matrix = np.linalg.inv(arr)
print(inv_matrix)


[[-2.   1. ]
 [ 1.5 -0.5]]


# pandas


In [ ]:
import pandas as pd
series = pd.Series([1, 2, 3])
print(series)


0    1
1    2
2    3
dtype: int64


In [ ]:
data = {'A': [1, 2], 'B': [3, 4]}
df = pd.DataFrame(data)
print(df)


   A  B
0  1  3
1  2  4


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.head(2))


   A  B
0  1  4
1  2  5


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.tail(2))


   A  B
1  2  5
2  3  6


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.describe())


         A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


In [ ]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
print(df.shape)


(2, 2)


In [ ]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
print(df.columns)


Index(['A', 'B'], dtype='object')


In [ ]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df_dropped = df.drop('A', axis=1)
print(df_dropped)


   B
0  3
1  4


In [ ]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df_renamed = df.rename(columns={'A': 'X'})
print(df_renamed)


   X  B
0  1  3
1  2  4


In [ ]:
df = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
print(df.isnull())


       A      B
0  False  False
1   True  False
2  False   True


In [ ]:
df = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
print(df.notnull())


       A      B
0   True   True
1  False   True
2   True  False


In [ ]:
df = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})
df_filled = df.fillna(0)
print(df_filled)


     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0


In [ ]:
df = pd.DataFrame({'A': [1, 1, 2], 'B': [3, 4, 5]})
grouped = df.groupby('A').sum()
print(grouped)


   B
A   
1  7
2  5


In [ ]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [1, 2], 'C': [5, 6]})
merged = pd.merge(df1, df2, on='A')
print(merged)


   A  B  C
0  1  3  5
1  2  4  6


In [ ]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'A': [3, 4]})
concatenated = pd.concat([df1, df2])
print(concatenated)



   A
0  1
1  2
0  3
1  4


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': ['X', 'X', 'Y']})
pivot = df.pivot_table(values='B', index='C', aggfunc='sum')
print(pivot)


   B
C   
X  9
Y  6


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3]})
result = df.apply(lambda x: x * 2)
print(result)


   A
0  2
1  4
2  6


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.iloc[1])


A    2
B    5
Name: 1, dtype: int64


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.loc[1, 'A'])


2


In [ ]:
df = pd.DataFrame({'A': [3, 1, 2], 'B': [6, 5, 4]})
sorted_df = df.sort_values(by='A')
print(sorted_df)


   A  B
1  1  5
2  2  4
0  3  6


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.corr())


     A    B
A  1.0  1.0
B  1.0  1.0


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3]})
print(df.cumsum())


   A
0  1
1  3
2  6


In [ ]:
df = pd.Series([1, 1, 2, 2, 3, 3, 3])
print(df.value_counts())


3    3
1    2
2    2
Name: count, dtype: int64


In [ ]:
df = pd.Series(['apple', 'banana', 'cherry'])
print(df.str.contains('a'))


0     True
1     True
2    False
dtype: bool


In [ ]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df.to_csv('output.csv')


In [ ]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df.to_excel('output.xlsx')


In [ ]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df.to_json('output.json')
